title: "Gobbledygooks" # the name of your site, e.g. ACME Corp.
tagline:      'Gobbledygooks by @riha78'
description:  'A random pile of .NET, BizTalk and integration focused scribbles by <a href="http://twitter.com/riha78">@riha78</a>.'
permalink:    /:title

url:          'http://richardhallgren.com'
baseurl: ''
author:
  name:       'Richard'
  email:      'richard.hallgren@gmail.com'



highligter:   true
paginate:     5
permalink:    /:title
# disqus_short_name: 'gobbledygooks'

plugins:
  - jekyll-postcss
  - jekyll-paginate

postcss:
  cache: false
