title: "Gobbledygooks" # the name of your site, e.g. ACME Corp.
tagline:      'Gobbledygooks by @riha78'
description:  'A random pile of .NET, BizTalk, Azure, and integration focused scribbles by Richard Hallgren.'
lang: en-US

url:          'https://richardhallgren.com'
baseurl: ''
author:
  name:       'Richard'
  email:      'richard.hallgren@gmail.com'



highlighter:   rouge
paginate:     5
permalink:    /:title
# disqus_short_name: 'gobbledygooks'

plugins:
  - jekyll-postcss
  - jekyll-paginate

postcss:
  cache: false
