title:        'Gobble&#173;dygooks'
tagline:      'Gobbledygooks by @riha78'
description:  'A random pile of .NET, BizTalk and integration focused scribbles by <a href="http://twitter.com/riha78">@riha78</a>.'
url:          http://richardhallgren.com
author:
  name:       'Richard'
  email:      'richard.hallgren@gmail.com'
markdown:     rdiscount
permalink:    pretty
highligter:     true
paginate:     5
