title:        richardhallgren.com
tagline:      'An other blog'
description:  '.NET, BizTalk and integration focused scribbles'
url:          http://richardhallgren.com
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
